mypos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from posapp import views

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('cart/',include('poscart.urls', namespace='cart')),
    path('', include('posapp.urls')),
    path('admin/', admin.site.urls),
    # path(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    
    #   This came from Tyler's project (I assume it is for authentication)
    path('', include('django.contrib.auth.urls')),
    
] 

poscart/urls.py
from django.urls import path
from . import views

app_name = 'poscart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

poscart/models.py
from django.db import models

# Create your models here.

poscart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

poscart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from posapp.models import Products
from .poscart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
        
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True}) 
    return render(request, 'cart/cart.html', {'cart': cart})

poscart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Shopping Cart
{% endblock %}


{% block content %}
<h1> Shopping Cart</h1>
<table width=1200px class="table table-inverse">
    <thead>
        <tr>
            <th class="table-primary">Image</th>
            <th class="table-primary">Product</th>
            <th class="table-primary">Quantity</th>
            <th class="table-primary">Remove</th>
            <th class="table-primary">Unit Price</th>
            <th class="table-primary">Price</th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with item.product as product %}
    <tr>
        <td>
            <img width="100px" src="https://as1.ftcdn.net/v2/jpg/03/11/87/52/1000_F_311875255_d57wDCwlZxdtOEwsnmXLHkV1r29i1R2U.jpg">
        </td>
        <td>{{product.name}}</td>
        {% comment %} <td>{{item.quantity}}</td> {% endcomment %}
        <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                {% csrf_token %}
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input class="btn btn-outline-primary js-btn-plus" type="submit"
                                                    value="Update">
                                            </form>
                                        </div>
                                    </div>
                                </td>
        <td>
            <form action = "{% url "cart:cart_remove" product.id %}" method = "post">
            <input type="submit" value ="Remove">
            {% csrf_token %}
            </form>
        </td>
        <td class = "num">${{item.price}}</td>
        <td class = "num">${{item.total_price}}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tbody>
</table>

<div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-6">
                        <a href="/checkout/"><button class="btn btn-outline-primary btn-sm btn-block">Checkout</button></a>
                    </div>
                </div>
{% endblock %}